/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Lager;
import model.collection.LagerbestandCollection;
import model.filter.LagerbestandFilterModel;

/**
 *
 * @author simon
 */
public class LagerbestandFilterFrame extends javax.swing.JFrame {
    private static LagerbestandFilterFrame singleton;
    
    public static LagerbestandFilterFrame getInstance(Component mainFrame)
    {
        if (LagerbestandFilterFrame.singleton == null){
            singleton = new LagerbestandFilterFrame(mainFrame);
        }
        singleton.setVisible(true);
        return singleton;
    }
    /**
     * Creates new form LagerBestandFilterFrame
     */
    public LagerbestandFilterFrame() {
        initComponents();
        try{
            loadHlCbx();
        }catch(SQLException ex){
            System.out.println("error");
        }
    }
    
    public LagerbestandFilterFrame(Component c) {
        this();
        alignFilterMenu(c);
    }
    
    public void alignFilterMenu(Component main)
    {
        int x = main.getX();
        int width = main.getPreferredSize().width;
        int rightBorder = x+width;
        int newOrigin = rightBorder -this.getWidth()-9;
        this.setLocation(newOrigin, this.getY()+210);
    }

    private void loadHlCbx() throws SQLException {
        cbxZ.removeAllItems();
        cbxX.removeAllItems();
        cbxY.removeAllItems();
        cbxZ.addItem("z");
        cbxX.addItem("x");
        cbxY.addItem("y");

        Lager hl = Lager.getLager(Lager.Lagerort.hochregal);
        int x = hl.getHoehe();
        int y = hl.getBreite();
        int z = hl.getTiefe();

        for (int i = 1; i <= x; i++) {
            cbxZ.addItem(i);
        }

        for (int i = 1; i <= y; i++) {
            cbxX.addItem(i);
        }

        for (int i = 1; i <= z; i++) {
            cbxY.addItem(i);
        }
    }
    
    private void loadFlCbx() throws SQLException {
        cbxZ.removeAllItems();
        cbxX.removeAllItems();
        cbxY.removeAllItems();
        cbxZ.addItem("z");
        cbxX.addItem("x");
        cbxY.addItem("y");

        Lager hl = Lager.getLager(Lager.Lagerort.freilager);
        int x = hl.getHoehe();
        int y = hl.getBreite();
        int z = hl.getTiefe();

        for (int i = 1; i <= x; i++) {
            cbxZ.addItem(i);
        }

        for (int i = 1; i <= y; i++) {
            cbxX.addItem(i);
        }

        for (int i = 1; i <= z; i++) {
            cbxY.addItem(i);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        cbxLagertyp = new javax.swing.JComboBox();
        lblFachadresse = new javax.swing.JLabel();
        lblGrund = new javax.swing.JLabel();
        lblMengeVon = new javax.swing.JLabel();
        lblFilter = new javax.swing.JLabel();
        cbxZ = new javax.swing.JComboBox();
        cbxX = new javax.swing.JComboBox();
        cbxY = new javax.swing.JComboBox();
        executeFilterButton = new javax.swing.JButton();
        lblMengeBis = new javax.swing.JLabel();
        txfMengeVon = new javax.swing.JTextField();
        txfMengeBis = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txfGrund = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxLagertyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "HL", "FL" }));
        cbxLagertyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLagertypActionPerformed(evt);
            }
        });

        lblFachadresse.setText("Fachadresse:");

        lblGrund.setText("Grund: ");

        lblMengeVon.setText("Menge von:");

        lblFilter.setText("Filter:");

        cbxZ.setModel(new javax.swing.DefaultComboBoxModel());

        cbxX.setModel(new javax.swing.DefaultComboBoxModel());
        cbxX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxXActionPerformed(evt);
            }
        });

        cbxY.setModel(new javax.swing.DefaultComboBoxModel());

        executeFilterButton.setText("Filter ausführen");
        executeFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeFilterButtonActionPerformed(evt);
            }
        });

        lblMengeBis.setText("Menge bis:");

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addComponent(lblGrund)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfGrund))
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                        .addComponent(lblMengeBis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfMengeBis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                        .addComponent(lblMengeVon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfMengeVon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFachadresse, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFilter, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(executeFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addComponent(cbxLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(cbxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGap(25, 25, 25))
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addComponent(lblFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFachadresse, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMengeVon)
                    .addComponent(txfMengeVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMengeBis)
                    .addComponent(txfMengeBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrund)
                    .addComponent(txfGrund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(executeFilterButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxXActionPerformed

    private void cbxLagertypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLagertypActionPerformed
       if(cbxLagertyp.getSelectedItem().equals("HL")){
            try {
                loadHlCbx();
            } catch (SQLException ex) {
                Logger.getLogger(BestandsaenderungFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                loadFlCbx();
            } catch (SQLException ex) {
                Logger.getLogger(BestandsaenderungFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbxLagertypActionPerformed

    private void executeFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeFilterButtonActionPerformed
        LagerbestandFilterModel lfm = new LagerbestandFilterModel();
        if (cbxLagertyp.getSelectedItem().toString().length() > 1) {
            lfm.setLagerTyp(getComboLager(cbxLagertyp.getSelectedItem().toString()));
        }
        if (!cbxX.getSelectedItem().toString().equals("x")) {
            lfm.setX((int) cbxX.getSelectedItem());
        }
        if (!cbxY.getSelectedItem().toString().equals("y")) {
            lfm.setY((int) cbxY.getSelectedItem());
        }
        if (!cbxZ.getSelectedItem().toString().equals("z")) {
            lfm.setZ((int) cbxZ.getSelectedItem());
        }

        if (!txfMengeVon.getText().isEmpty()) {
            lfm.setVonMenge(Integer.parseInt(txfMengeVon.getText()));
        }
        if (!txfMengeBis.getText().isEmpty()) {
            lfm.setBisMenge(Integer.parseInt(txfMengeBis.getText()));
        }
        if (!txfGrund.getText().isEmpty()) {
            lfm.setGrund(txfGrund.getText());
        }
        try{
            LagerbestandCollection lbc = new LagerbestandCollection();
            LagerbestandCollection result = lbc.addFilter(lfm);
        } catch (SQLException ex) {
            Logger.getLogger(LagerbestandFilterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_executeFilterButtonActionPerformed

    public static Lager.Lagerort getComboLager(String s){
        switch(s){
            case "HL":
                return Lager.Lagerort.hochregal;
            case "FL":
                return Lager.Lagerort.freilager;
            default:
                return null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LagerbestandFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LagerbestandFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LagerbestandFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LagerbestandFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LagerbestandFilterFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxLagertyp;
    private javax.swing.JComboBox cbxX;
    private javax.swing.JComboBox cbxY;
    private javax.swing.JComboBox cbxZ;
    private javax.swing.JButton executeFilterButton;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFachadresse;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblGrund;
    private javax.swing.JLabel lblMengeBis;
    private javax.swing.JLabel lblMengeVon;
    private javax.swing.JPanel panMain;
    private javax.swing.JTextField txfGrund;
    private javax.swing.JTextField txfMengeBis;
    private javax.swing.JTextField txfMengeVon;
    // End of variables declaration//GEN-END:variables
}
