/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helper.FilterUiHelper;
import helper.Misc;
import java.awt.Component;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JTable;
import model.Lager;
import model.collection.LagerbestandCollection;
import model.filter.LagerbestandFilterModel;
import model.table.LagerbestandTableModel;

/**
 * Filter Fenster für den Lagerbestand
 * @author simon
 */
public class LagerbestandFilterFrame extends javax.swing.JFrame {
    private static LagerbestandFilterFrame singleton;
    JTable lagerBestandTable;
    
    /** 
     * Methode zum holen einer Filter Instanz
     * @param mainFrame Hauptfenster 
     * @param jtable Lagerbestand Tabelle
     * @return
     */
    public static LagerbestandFilterFrame getInstance(Component mainFrame, JTable jtable)
    {
        if (LagerbestandFilterFrame.singleton == null){
            singleton = new LagerbestandFilterFrame(mainFrame, jtable);
        }
        singleton.setVisible(true);
        return singleton;
    }
    
    /**
     * Creates new form LagerBestandFilterFrame
     */
    public LagerbestandFilterFrame() {
        initComponents();
        try{
            loadCbx();
        }catch(SQLException ex){
            Misc.printSQLException(this, ex);
        }
    }
    
    /**
     * Konstruktor 
     * @param c Hauptfenster
     * @param jtable Lagerbestand Tabelle
      */
    public LagerbestandFilterFrame(Component c, JTable jtable) {
        this();
        alignFilterMenu(c);
        lagerBestandTable = jtable;
    }
    
    /**
     * Richtet den Filter rechtsbündig zum Hauptfenster aus
     * @param main
     */
    public void alignFilterMenu(Component main)
    {
        int x = main.getX();
        int width = main.getPreferredSize().width;
        int rightBorder = x+width;
        int newOrigin = rightBorder -this.getWidth()-9;
        this.setLocation(newOrigin, this.getY()+210);
    }
    
    /**
     * Füllt die QuellComboBoxen mit den größtmöglichen Werten
     * @author ssinger
     * @throws SQLException
     */
    private void loadCbx() throws SQLException {
        cbxZ.removeAllItems();
        cbxX.removeAllItems();
        cbxY.removeAllItems();
        cbxZ.addItem("z");
        cbxX.addItem("x");
        cbxY.addItem("y");

        int x = 0;
        int y = 0;
        int z = 0;
        
        Lager fl = Lager.getLager(Lager.Lagerort.freilager);
        Lager hl = Lager.getLager(Lager.Lagerort.hochregal);
        
        if(hl.getHoehe() > fl.getHoehe()){
            x = hl.getHoehe();
        }else{
            x = fl.getHoehe();
        }
        
        if(hl.getBreite() > fl.getBreite()){
            y = hl.getBreite();
        }else{
            y = fl.getBreite();
        }
        
        if(hl.getTiefe() > fl.getTiefe()){
            z = hl.getTiefe();
        }else{
            z = fl.getTiefe();
        }
        
        for (int i = 1; i <= x; i++) {
            cbxZ.addItem(i);
        }

        for (int i = 1; i <= y; i++) {
            cbxX.addItem(i);
        }

        for (int i = 1; i <= z; i++) {
            cbxY.addItem(i);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        cbxLagertyp = new javax.swing.JComboBox();
        lblFachadresse = new javax.swing.JLabel();
        lblGrund = new javax.swing.JLabel();
        lblMengeVon = new javax.swing.JLabel();
        lblFilter = new javax.swing.JLabel();
        cbxZ = new javax.swing.JComboBox();
        cbxX = new javax.swing.JComboBox();
        cbxY = new javax.swing.JComboBox();
        executeFilterButton = new javax.swing.JButton();
        lblMengeBis = new javax.swing.JLabel();
        txfMengeVon = new javax.swing.JTextField();
        txfMengeBis = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txfGrund = new javax.swing.JTextField();
        lblBezeichnung = new javax.swing.JLabel();
        txfBezeichnung = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxLagertyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "HL", "FL" }));

        lblFachadresse.setText("Fachadresse:");

        lblGrund.setText("Grund: ");

        lblMengeVon.setText("Menge von:");

        lblFilter.setText("Filter:");

        cbxZ.setModel(new javax.swing.DefaultComboBoxModel());

        cbxX.setModel(new javax.swing.DefaultComboBoxModel());

        cbxY.setModel(new javax.swing.DefaultComboBoxModel());

        executeFilterButton.setText("Filter ausführen");
        executeFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeFilterButtonActionPerformed(evt);
            }
        });

        lblMengeBis.setText("Menge bis:");

        lblBezeichnung.setText("Bezeichnung:");

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                        .addComponent(lblMengeBis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfMengeBis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                        .addComponent(lblMengeVon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfMengeVon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(executeFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbxLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(cbxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addComponent(lblGrund)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfGrund, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFachadresse)
                            .addComponent(lblFilter))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addComponent(lblBezeichnung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfBezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addComponent(lblFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFachadresse, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addComponent(lblBezeichnung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrund)
                            .addComponent(txfGrund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMengeVon)
                            .addComponent(txfMengeVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMengeBis)
                            .addComponent(txfMengeBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(executeFilterButton))
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addComponent(txfBezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Validiert die Eingabe, erzeugt ein neues LagerbestandFilterModel und
     * refreshed die Lagerbestandstabelle
     * @param evt 
     */
    private void executeFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeFilterButtonActionPerformed
        
        HashMap<Integer, String> errors = FilterUiHelper.getInstance().validateLagerFilter(
                txfMengeVon.getText(),
                txfMengeBis.getText()
                );
        
        if(Misc.createErrorDialog(this, errors) == true){
            return;
        }
        
        LagerbestandFilterModel lfm = FilterUiHelper.createLFM(
                cbxLagertyp.getSelectedItem().toString(),
                cbxX.getSelectedItem().toString(),
                cbxY.getSelectedItem().toString(),
                cbxZ.getSelectedItem().toString(),
                txfMengeVon.getText(),
                txfMengeBis.getText(),
                txfGrund.getText(),
                txfBezeichnung.getText());

        try{
           refreshLagerbestandTableModel(lfm);
        } catch (SQLException ex) {
            Misc.printSQLException(this, ex);
        }
        this.dispose();
    }//GEN-LAST:event_executeFilterButtonActionPerformed

    /**
     * Läd die Lagerbestandstabelle mit den übergenenen Filtereinstellungen
     * nach
     */ 
    private void refreshLagerbestandTableModel(LagerbestandFilterModel lfm) throws SQLException {
        LagerbestandCollection lc = LagerbestandCollection.getInstance().applyFilter(lfm);
        LagerbestandTableModel lm = new LagerbestandTableModel();
        lm.setData(lc);
        lagerBestandTable.setModel(lm);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxLagertyp;
    private javax.swing.JComboBox cbxX;
    private javax.swing.JComboBox cbxY;
    private javax.swing.JComboBox cbxZ;
    private javax.swing.JButton executeFilterButton;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBezeichnung;
    private javax.swing.JLabel lblFachadresse;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblGrund;
    private javax.swing.JLabel lblMengeBis;
    private javax.swing.JLabel lblMengeVon;
    private javax.swing.JPanel panMain;
    private javax.swing.JTextField txfBezeichnung;
    private javax.swing.JTextField txfGrund;
    private javax.swing.JTextField txfMengeBis;
    private javax.swing.JTextField txfMengeVon;
    // End of variables declaration//GEN-END:variables
}
