package view;

import javax.swing.JTable;
import javax.swing.table.TableColumn;
import models.tables.LagerbestandTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author simon
 */
public class LagerbestandPanel extends javax.swing.JPanel {
    MainFrame mainFrame;
    /**
     * Creates new form LagerbestandPanel
     */
    public LagerbestandPanel() {
        initComponents();
    }
    
    public void setTableWidths(JTable table)
    {
        int[] arrWidths = {50, 110, 10, 10, 10, 110,70, 50, 150};
        TableColumn tc;
        table.setRowHeight(23);
        int i = 0;
        for (int width : arrWidths){
            tc = table.getColumnModel().getColumn(i++);
            tc.setPreferredWidth(width);
        }
    }
    
    public void setMainFrame(MainFrame mainFrame)
    {
        this.mainFrame = mainFrame;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        teilEinlagernButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        teilUmlagernButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        teilAuslagernButton = new javax.swing.JButton();
        teilSplittenButton = new javax.swing.JButton();
        filternButton = new javax.swing.JButton();

        LagerbestandTableModel tm = new LagerbestandTableModel();
        tm.setData(tm.dummyArrayList());
        jTable1.setModel(tm);
        setTableWidths(jTable1);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Lagerbestand");

        teilEinlagernButton.setText("Teile einlagern");
        teilEinlagernButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teilEinlagernButtonActionPerformed(evt);
            }
        });

        jButton3.setText("suchen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        teilUmlagernButton.setText("Teile umlagern");
        teilUmlagernButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teilUmlagernButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Freitextsuche:");

        jButton1.setText("Filter zurücksetzen");

        teilAuslagernButton.setText("Teile auslagern");
        teilAuslagernButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teilAuslagernButtonActionPerformed(evt);
            }
        });

        teilSplittenButton.setText("Teile splitten");
        teilSplittenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teilSplittenButtonActionPerformed(evt);
            }
        });

        filternButton.setText("Filtern");
        filternButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filternButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teilEinlagernButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teilAuslagernButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teilUmlagernButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teilSplittenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291)
                        .addComponent(filternButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel12)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filternButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teilEinlagernButton)
                    .addComponent(teilAuslagernButton)
                    .addComponent(teilUmlagernButton)
                    .addComponent(teilSplittenButton))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void teilEinlagernButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teilEinlagernButtonActionPerformed
        BestandsaenderungFrame bestandsaenderungFrame = new BestandsaenderungFrame(true);
        bestandsaenderungFrame.setVisible(true);
    }//GEN-LAST:event_teilEinlagernButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void teilUmlagernButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teilUmlagernButtonActionPerformed
        UmlagernFrame umlagernframe = new UmlagernFrame();
        umlagernframe.setVisible(true);
    }//GEN-LAST:event_teilUmlagernButtonActionPerformed

    private void teilAuslagernButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teilAuslagernButtonActionPerformed
        BestandsaenderungFrame bestandsaenderungFrame = new BestandsaenderungFrame();
        bestandsaenderungFrame.setVisible(true);
    }//GEN-LAST:event_teilAuslagernButtonActionPerformed

    private void teilSplittenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teilSplittenButtonActionPerformed
        UmlagernFrame umlagernframe = new UmlagernFrame(true);
        umlagernframe.setVisible(true);
    }//GEN-LAST:event_teilSplittenButtonActionPerformed

    private void filternButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filternButtonActionPerformed
        new LagerbestandFilterFrame(mainFrame).setVisible(true);
    }//GEN-LAST:event_filternButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filternButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton teilAuslagernButton;
    private javax.swing.JButton teilEinlagernButton;
    private javax.swing.JButton teilSplittenButton;
    private javax.swing.JButton teilUmlagernButton;
    // End of variables declaration//GEN-END:variables
}
