package view;

import controller.NavigationController;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author simon
 */
public class MainFrame extends javax.swing.JFrame {

    NavigationController navigationController;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public JPanel getStartPanel() {
        return this.startPanel;
    }
    
    public void addNaviController(NavigationController navigationController) {
        this.navigationController = navigationController;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        initPanel = new view.InitPanel();
        loginPanel = new view.LoginPanel();
        mainPanel = new view.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 768));
        setName("StartPanel"); // NOI18N

        startPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        startPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        startPanel.setLayout(new java.awt.CardLayout());

        initPanel.setMainFrame(this);
        startPanel.add(initPanel, "init");

        loginPanel.setMainFrame(this);
        loginPanel.setMinimumSize(new java.awt.Dimension(1024, 768));
        loginPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        startPanel.add(loginPanel, "login");

        loginPanel.setMainFrame(this);
        mainPanel.setMinimumSize(new java.awt.Dimension(1000, 844));
        startPanel.add(mainPanel, "main");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("StartPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.InitPanel initPanel;
    private view.LoginPanel loginPanel;
    private view.MainPanel mainPanel;
    private javax.swing.JPanel startPanel;
    // End of variables declaration//GEN-END:variables
}
