package view;

import controller.NavigationController;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author simon
 */
public class MainPanel extends javax.swing.JPanel {
    MainFrame mainFrame;
    NavigationController navigationController;
   
    /**
     * Creates new form TeilebestandPanel
     */
    public MainPanel() {
        initComponents();
        navigationController = new NavigationController(cardPanel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationBar = new javax.swing.JPanel();
        btnTeilebestand = new javax.swing.JButton();
        btnLagerbestand = new javax.swing.JButton();
        btnWarenbewegung = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        teilebestandPanel = new view.TeilebestandPanel();
        lagerbestandPanel = new view.LagerbestandPanel();
        warenbewegungPanel = new view.WarenbewegungPanel();

        setMinimumSize(new java.awt.Dimension(1000, 744));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 844));
        setLayout(new java.awt.BorderLayout());

        btnTeilebestand.setBackground(new java.awt.Color(255, 255, 51));
        btnTeilebestand.setText("Teilebestand");
        btnTeilebestand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeilebestandActionPerformed(evt);
            }
        });

        btnLagerbestand.setBackground(new java.awt.Color(255, 255, 255));
        btnLagerbestand.setText("Lagerbestand");
        btnLagerbestand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLagerbestandActionPerformed(evt);
            }
        });

        btnWarenbewegung.setBackground(new java.awt.Color(255, 255, 255));
        btnWarenbewegung.setText("Warenbewegung");
        btnWarenbewegung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarenbewegungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationBarLayout = new javax.swing.GroupLayout(navigationBar);
        navigationBar.setLayout(navigationBarLayout);
        navigationBarLayout.setHorizontalGroup(
            navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnTeilebestand, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLagerbestand, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnWarenbewegung, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        navigationBarLayout.setVerticalGroup(
            navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeilebestand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLagerbestand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWarenbewegung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(navigationBar, java.awt.BorderLayout.NORTH);

        cardPanel.setLayout(new java.awt.CardLayout());
        cardPanel.add(teilebestandPanel, "teilebestand");
        cardPanel.add(lagerbestandPanel, "lagerbestand");
        cardPanel.add(warenbewegungPanel, "warenbewegung");

        add(cardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLagerbestandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagerbestandActionPerformed
       navigationController.showCard("lagerbestand");
    }//GEN-LAST:event_btnLagerbestandActionPerformed

    private void btnTeilebestandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeilebestandActionPerformed
       navigationController.showCard("teilebestand");
    }//GEN-LAST:event_btnTeilebestandActionPerformed

    private void btnWarenbewegungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarenbewegungActionPerformed
       navigationController.showCard("warenbewegung");
    }//GEN-LAST:event_btnWarenbewegungActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLagerbestand;
    private javax.swing.JButton btnTeilebestand;
    private javax.swing.JButton btnWarenbewegung;
    private javax.swing.JPanel cardPanel;
    private view.LagerbestandPanel lagerbestandPanel;
    private javax.swing.JPanel navigationBar;
    private view.TeilebestandPanel teilebestandPanel;
    private view.WarenbewegungPanel warenbewegungPanel;
    // End of variables declaration//GEN-END:variables
}
