package view;

import controller.NavigationController;
import java.awt.Color;

/**
 * Die Klasse des Hauptpanel
 * 
 * @author simon
 */
public class MainPanel extends javax.swing.JPanel {
    MainFrame mainFrame;
    NavigationController navigationController;
   
    /**
     * Creates new form TeilebestandPanel
     */
    public MainPanel() {
        initComponents();
        navigationController = new NavigationController(panCard);
    }
    
    /**
    * Übergibt den MainFrame
    * 
    */
    public void setMainFrame(MainFrame mainFrame)
    {
        this.mainFrame = mainFrame;
        panTeilebestand.setMainFrame(mainFrame);
        panLagerbestand.setMainFrame(mainFrame);
        panWarenbewegung.setMainFrame(mainFrame);
    }
    
    /**
    * Gibt LagerbestandPanel zurück
    * 
    */
    public LagerbestandPanel getLagerbestand()
    {
        return panLagerbestand;
    }
    
    /**
    * Gibt TeilebestandPanel zurück
    * 
    */
    public TeilebestandPanel getTeilebestand()
    {
        return panTeilebestand;
    }
    
    /**
    * Gibt WarenbewegungPanel zurück
    * 
    */
    public WarenbewegungPanel getWarenbewegung()
    {
        return panWarenbewegung;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNavigationBar = new javax.swing.JPanel();
        btnTeilebestand = new javax.swing.JButton();
        btnLagerbestand = new javax.swing.JButton();
        btnWarenbewegung = new javax.swing.JButton();
        panCard = new javax.swing.JPanel();
        panTeilebestand = new view.TeilebestandPanel();
        panLagerbestand = new view.LagerbestandPanel();
        panWarenbewegung = new view.WarenbewegungPanel();

        setMinimumSize(new java.awt.Dimension(1000, 744));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 844));
        setLayout(new java.awt.BorderLayout());

        panNavigationBar.setLayout(new java.awt.GridLayout(1, 3));

        btnTeilebestand.setBackground(new java.awt.Color(255, 255, 51));
        btnTeilebestand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/schrauben.png"))); // NOI18N
        btnTeilebestand.setText("    Teilebestand");
        btnTeilebestand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTeilebestand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeilebestandActionPerformed(evt);
            }
        });
        panNavigationBar.add(btnTeilebestand);

        btnLagerbestand.setBackground(new java.awt.Color(255, 255, 255));
        btnLagerbestand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/lagerBestand.gif"))); // NOI18N
        btnLagerbestand.setText("  Lagerbestand");
        btnLagerbestand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLagerbestand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLagerbestandActionPerformed(evt);
            }
        });
        panNavigationBar.add(btnLagerbestand);

        btnWarenbewegung.setBackground(new java.awt.Color(255, 255, 255));
        btnWarenbewegung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/lagerBewegung.gif"))); // NOI18N
        btnWarenbewegung.setText("  Warenbewegung");
        btnWarenbewegung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnWarenbewegung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarenbewegungActionPerformed(evt);
            }
        });
        panNavigationBar.add(btnWarenbewegung);

        add(panNavigationBar, java.awt.BorderLayout.NORTH);

        panCard.setLayout(new java.awt.CardLayout());
        panCard.add(panTeilebestand, "teilebestand");
        panCard.add(panLagerbestand, "lagerbestand");
        panCard.add(panWarenbewegung, "warenbewegung");

        add(panCard, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Schaltet das Fenster auf Lagerbestand um
    * 
    */
    private void btnLagerbestandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagerbestandActionPerformed
       navigationController.showCard("lagerbestand");
       highlightButton("lagerbestand");
    }//GEN-LAST:event_btnLagerbestandActionPerformed

    /**
    * Schaltet das Fenster auf Teilebestand um
    * 
    */
    private void btnTeilebestandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeilebestandActionPerformed
       navigationController.showCard("teilebestand");
       highlightButton("teilebestand");
    }//GEN-LAST:event_btnTeilebestandActionPerformed

    /**
    * Schaltet das Fenster auf Warenbewegung um
    * 
    */
    private void btnWarenbewegungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarenbewegungActionPerformed
       navigationController.showCard("warenbewegung");
       highlightButton("warenbewegung");
    }//GEN-LAST:event_btnWarenbewegungActionPerformed
    
    /**
    * Bringt das ausgewählte Menüelement zum Leuchten
    * 
    */
    private void highlightButton(String name){
        btnLagerbestand.setBackground(Color.white);
        btnTeilebestand.setBackground(Color.white);
        btnWarenbewegung.setBackground(Color.white);
        Color color = Color.yellow;
        switch(name){
            case "lagerbestand":
                btnLagerbestand.setBackground(color);
                break;
            case "teilebestand":
                btnTeilebestand.setBackground(color);
                break;
            case "warenbewegung":
                btnWarenbewegung.setBackground(color);
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLagerbestand;
    private javax.swing.JButton btnTeilebestand;
    private javax.swing.JButton btnWarenbewegung;
    private javax.swing.JPanel panCard;
    private view.LagerbestandPanel panLagerbestand;
    private javax.swing.JPanel panNavigationBar;
    private view.TeilebestandPanel panTeilebestand;
    private view.WarenbewegungPanel panWarenbewegung;
    // End of variables declaration//GEN-END:variables
}
