/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.j256.ormlite.dao.Dao;
import helper.DatabaseManager;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import model.Lager;
import model.Lager;
import model.Teilebestand;
import model.collection.TeilebestandCollection;
import model.filter.TeilebestandFilterModel;
import model.table.TeileTableModel;

/**
 *
 * @author simon
 */
public class TeileFilterFrame extends javax.swing.JFrame {
    private static TeileFilterFrame singleton;
    JTable teileBestandTable;
    
    public static TeileFilterFrame getInstance(Component mainFrame, JTable jtable)
    {
        if (TeileFilterFrame.singleton == null){
            singleton = new TeileFilterFrame(mainFrame, jtable);
        }
        singleton.setVisible(true);
        return singleton;
    }
    /**
     * Creates new form TeileFilter
     */
    public TeileFilterFrame() {
        
        initComponents();
    }
    
    public TeileFilterFrame(Component c, JTable jtable) {
        this();
        alignFilterMenu(c);
        teileBestandTable = jtable;
    }
    
    public void alignFilterMenu(Component main)
    {
        int x = main.getX();
        int width = main.getPreferredSize().width;
        int rightBorder = x+width;
        int newOrigin = rightBorder -this.getWidth()-9;
        this.setLocation(newOrigin, this.getY()+198);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        lblTeiltyp = new javax.swing.JLabel();
        cbxTeiltyp = new javax.swing.JComboBox();
        lblFilter = new javax.swing.JLabel();
        lblTeil = new javax.swing.JLabel();
        btnExecuteFilter = new javax.swing.JButton();
        cbxTeil = new javax.swing.JComboBox();
        lblLagertyp = new javax.swing.JLabel();
        cbxLagertyp = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        lblMaterialgruppe = new javax.swing.JLabel();
        txfMaterialgruppe = new javax.swing.JTextField();
        lblVolumeneinheiten = new javax.swing.JLabel();
        txfVeVon = new javax.swing.JTextField();
        lblVEvon = new javax.swing.JLabel();
        lblVEbis = new javax.swing.JLabel();
        txfVeBis = new javax.swing.JTextField();
        lblPreisVon = new javax.swing.JLabel();
        txfPreisVon = new javax.swing.JTextField();
        lblZeichnungsnummer = new javax.swing.JLabel();
        txfZeichnungsnummer = new javax.swing.JTextField();
        lblPreisBis = new javax.swing.JLabel();
        txfPreisBis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTeiltyp.setText("Typ:");

        cbxTeiltyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kaufteile", "Werkzeuge", "unfertige Baugruppe", "Vorratsteile", "Vorrichtungen" }));

        lblFilter.setText("Filter:");

        lblTeil.setText("Bezeichnung:");

        btnExecuteFilter.setText("Filter ausführen");
        btnExecuteFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteFilterActionPerformed(evt);
            }
        });

        cbxTeil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Schrauben", "Erdbeeren", "Waffeleisen", "Büffelmozarella" }));
        cbxTeil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTeilActionPerformed(evt);
            }
        });

        lblLagertyp.setText("Lagertyp:");

        cbxLagertyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hochregallager", "Freilager" }));

        lblMaterialgruppe.setText("Materialgruppe:");

        lblVolumeneinheiten.setText("Größe in Volumeneinheiten:");

        lblVEvon.setText("von:");

        lblVEbis.setText("bis:");

        txfVeBis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfVeBisActionPerformed(evt);
            }
        });

        lblPreisVon.setText("Preis von:");

        lblZeichnungsnummer.setText("Zeichnungsnummer:");

        lblPreisBis.setText("Preis bis:");

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTeiltyp)
                            .addComponent(lblFilter)
                            .addComponent(lblTeil)
                            .addComponent(lblMaterialgruppe)
                            .addComponent(lblZeichnungsnummer)
                            .addComponent(lblVolumeneinheiten))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addGap(108, 108, 108))
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExecuteFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfZeichnungsnummer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panMainLayout.createSequentialGroup()
                                .addComponent(lblPreisBis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txfPreisBis, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panMainLayout.createSequentialGroup()
                                .addComponent(lblPreisVon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txfPreisVon, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txfMaterialgruppe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTeiltyp, javax.swing.GroupLayout.Alignment.LEADING, 0, 193, Short.MAX_VALUE)
                            .addComponent(cbxTeil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLagertyp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxLagertyp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panMainLayout.createSequentialGroup()
                                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVEvon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVEbis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfVeBis, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(txfVeVon))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addComponent(lblFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLagertyp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTeil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTeil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTeiltyp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTeiltyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMaterialgruppe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfMaterialgruppe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVolumeneinheiten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfVeVon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVEvon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVEbis)
                    .addComponent(txfVeBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPreisVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreisVon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPreisBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreisBis))
                .addGap(18, 18, 18)
                .addComponent(lblZeichnungsnummer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfZeichnungsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnExecuteFilter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTeilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTeilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTeilActionPerformed

    private void txfVeBisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfVeBisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfVeBisActionPerformed

    private void btnExecuteFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteFilterActionPerformed
        TeilebestandFilterModel tfm = new TeilebestandFilterModel();
        
        if (!txfMaterialgruppe.getText().isEmpty()) {
            tfm.setMaterialgruppe(txfMaterialgruppe.getText());
        }
        if (!txfZeichnungsnummer.getText().isEmpty()) {
            tfm.setZeichnungsnummer(txfZeichnungsnummer.getText());
        }
        if (!txfPreisVon.getText().isEmpty()) {
            tfm.setVonPreis(Float.parseFloat(txfPreisVon.getText()));
        }
        if (!txfPreisBis.getText().isEmpty()) {
            tfm.setBisPreis(Float.parseFloat(txfPreisBis.getText()));
        }
        if (!txfVeVon.getText().isEmpty()) {
            tfm.setVonVe(Integer.parseInt(txfVeVon.getText()));
        }
        if (!txfVeBis.getText().isEmpty()) {
            tfm.setBisVe(Integer.parseInt(txfVeBis.getText()));
        }
        try {
            refreshTeilebestandTableModel(tfm);
        } catch (SQLException ex) {
            Logger.getLogger(TeileFilterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnExecuteFilterActionPerformed

    private void refreshTeilebestandTableModel(TeilebestandFilterModel tfm) throws SQLException{
        TeilebestandCollection tc = TeilebestandCollection.getInstance(tfm);
        TeileTableModel tm = new TeileTableModel();     
        tm.setData(tc);
        teileBestandTable.setModel(tm);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeileFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeileFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeileFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeileFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeileFilterFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecuteFilter;
    private javax.swing.JComboBox cbxLagertyp;
    private javax.swing.JComboBox cbxTeil;
    private javax.swing.JComboBox cbxTeiltyp;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblLagertyp;
    private javax.swing.JLabel lblMaterialgruppe;
    private javax.swing.JLabel lblPreisBis;
    private javax.swing.JLabel lblPreisVon;
    private javax.swing.JLabel lblTeil;
    private javax.swing.JLabel lblTeiltyp;
    private javax.swing.JLabel lblVEbis;
    private javax.swing.JLabel lblVEvon;
    private javax.swing.JLabel lblVolumeneinheiten;
    private javax.swing.JLabel lblZeichnungsnummer;
    private javax.swing.JPanel panMain;
    private javax.swing.JTextField txfMaterialgruppe;
    private javax.swing.JTextField txfPreisBis;
    private javax.swing.JTextField txfPreisVon;
    private javax.swing.JTextField txfVeBis;
    private javax.swing.JTextField txfVeVon;
    private javax.swing.JTextField txfZeichnungsnummer;
    // End of variables declaration//GEN-END:variables
}
