package view;

import helper.Misc;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import model.Teilebestand;
import model.collection.TeilebestandCollection;
import model.table.TeileTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author simon
 */
public class TeilebestandPanel extends javax.swing.JPanel {
    MainFrame mainFrame;
    /**
     * Creates new form TeilebestandPanel
     */
    public TeilebestandPanel() {
        initComponents();
        
    }
    
    public void setGuest()
    {
        this.pnlActions.setVisible(false);
    }
    
    public void setMainFrame(MainFrame mainFrame)
    {
        this.mainFrame = mainFrame;
    }
    
    public JTable getTeileTable()
    {
    return tblMain;
    }
    
    public void setTableWidths(JTable table)
    {
        int[] arrWidths = {35, 130, 130, 130, 50, 120,50};
        TableColumn tc;
        table.setRowHeight(23);
        int i = 0;
        for (int width : arrWidths){
            tc = table.getColumnModel().getColumn(i++);
            tc.setPreferredWidth(width);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTeilebestand = new javax.swing.JLabel();
        scpMain = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        btnFilterZurücksetzen = new javax.swing.JButton();
        btnFiltern = new javax.swing.JButton();
        pnlActions = new javax.swing.JPanel();
        lblAktionSelektiert = new javax.swing.JLabel();
        btnteilEinlagern = new javax.swing.JButton();
        btnNeuesTeil = new javax.swing.JButton();
        btnTeilAendern = new javax.swing.JButton();
        btnTeilLoschen = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1020, 761));

        lblTeilebestand.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTeilebestand.setText("Teilebestand");

        TeileTableModel tm = new TeileTableModel();
        tm.setData(TeilebestandCollection.getInstance());
        tblMain.setAutoCreateRowSorter(true);
        tblMain.setSelectionMode(ListSelectionModel.SINGLE_SELECTION );
        tblMain.setModel(tm);
        setTableWidths(tblMain);
        tblMain.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scpMain.setViewportView(tblMain);

        btnFilterZurücksetzen.setText("Filter zurücksetzen");
        btnFilterZurücksetzen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterZurücksetzenActionPerformed(evt);
            }
        });

        btnFiltern.setText("Filtern");
        btnFiltern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilternActionPerformed(evt);
            }
        });

        lblAktionSelektiert.setText("Aktionen selektiert:");

        btnteilEinlagern.setText("Teil einlagern");
        btnteilEinlagern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnteilEinlagernActionPerformed(evt);
            }
        });

        btnNeuesTeil.setText("Neues Teil anlegen");
        btnNeuesTeil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeuesTeilActionPerformed(evt);
            }
        });

        btnTeilAendern.setText("Teil bearbeiten");
        btnTeilAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeilAendernActionPerformed(evt);
            }
        });

        btnTeilLoschen.setText("Teil löschen");
        btnTeilLoschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeilLoschenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActionsLayout = new javax.swing.GroupLayout(pnlActions);
        pnlActions.setLayout(pnlActionsLayout);
        pnlActionsLayout.setHorizontalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAktionSelektiert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTeilAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTeilLoschen, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnteilEinlagern, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnNeuesTeil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlActionsLayout.setVerticalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAktionSelektiert)
                    .addComponent(btnTeilLoschen)
                    .addComponent(btnTeilAendern)
                    .addComponent(btnteilEinlagern)
                    .addComponent(btnNeuesTeil))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scpMain)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(695, 695, 695)
                                .addComponent(btnFiltern)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFilterZurücksetzen))
                            .addComponent(lblTeilebestand, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTeilebestand, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFilterZurücksetzen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltern))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNeuesTeilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeuesTeilActionPerformed
        TeilFrame teilframe = new TeilFrame();
        teilframe.setVisible(true);
        teilframe.setTable(tblMain);
    }//GEN-LAST:event_btnNeuesTeilActionPerformed

    private void btnTeilAendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeilAendernActionPerformed
         int selectedId;
        if(tblMain.getSelectedRow() >=0){
            selectedId = Integer.parseInt(tblMain.getValueAt(tblMain.getSelectedRow(), 0).toString());
            TeilFrame teilframe = new TeilFrame(true);
            try {
                teilframe.initTeil(selectedId);
            } catch (SQLException ex) {
                Misc.printSQLException(teilframe, ex);
            }
            teilframe.setVisible(true);
            teilframe.setTable(tblMain);
        }
        else{
            Misc.createErrorDialog(mainFrame, "Es muss erst ein Teil zum Ändern aus der "
                    + "Liste gewählt werden!");
        }
    }//GEN-LAST:event_btnTeilAendernActionPerformed

    private void btnTeilLoschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeilLoschenActionPerformed
        int selectedId;
        if(tblMain.getSelectedRow() >=0){
            selectedId = Integer.parseInt(tblMain.getValueAt(tblMain.getSelectedRow(), 0).toString());
            Teilebestand teil;
            int option = JOptionPane.showConfirmDialog(this, "Soll das Teil wirklich aus dem Teilebestand gelöscht werden?", " Teil löschen?", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                try {
                    teil = Teilebestand.loadTeil(selectedId);
                    teil.setDeleted(true);
                } catch (SQLException ex) {
                    Misc.printSQLException(mainFrame, ex);
                }
            refreshTeilebestandTableModel();       
            }
        }
        else{
            Misc.createErrorDialog(mainFrame, "Es muss erst ein Teil zum Löschen aus der "
                    + "Liste gewählt werden!");
        }
    }//GEN-LAST:event_btnTeilLoschenActionPerformed

    private void btnFilternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilternActionPerformed
       TeileFilterFrame.getInstance(mainFrame, tblMain);
    }//GEN-LAST:event_btnFilternActionPerformed

    private void btnteilEinlagernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnteilEinlagernActionPerformed
        int selectedId;
        if(tblMain.getSelectedRow() >=0){
        selectedId = Integer.parseInt(tblMain.getValueAt(tblMain.getSelectedRow(), 0).toString());
            try {
                BestandsaenderungFrame bestandsaenderungFrame = new BestandsaenderungFrame(
                BestandsaenderungFrame.EINLAGERN_TEILEBESTAND, selectedId, 0);
                bestandsaenderungFrame.setVisible(true);
                JTable lagerbestand = mainFrame.getPanMain().getLagerbestand().gettabMain();
                JTable warenbewegung = mainFrame.getPanMain().getWarenbewegung().gettabMain();

                bestandsaenderungFrame.setTable(lagerbestand);
                bestandsaenderungFrame.setTeileTable(tblMain);
                bestandsaenderungFrame.setWarenBewegungTable(warenbewegung);
            } catch (SQLException ex) {
                Misc.printSQLException(mainFrame, ex);
            }
        }
        else{
            Misc.createErrorDialog(mainFrame, "Es muss erst ein Teil zum Einlagern aus der "
                    + "Liste gewählt werden!");
        }
    }//GEN-LAST:event_btnteilEinlagernActionPerformed

    private void btnFilterZurücksetzenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterZurücksetzenActionPerformed
        refreshTeilebestandTableModel();
    }//GEN-LAST:event_btnFilterZurücksetzenActionPerformed

    /**
     * läd die Teilebestandtabelle neu
     */
    private void refreshTeilebestandTableModel() {
        TeilebestandCollection tc = TeilebestandCollection.getInstance(true);
        TeileTableModel tm = new TeileTableModel();
        tm.setData(tc);
        tblMain.setModel(tm);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilterZurücksetzen;
    private javax.swing.JButton btnFiltern;
    private javax.swing.JButton btnNeuesTeil;
    private javax.swing.JButton btnTeilAendern;
    private javax.swing.JButton btnTeilLoschen;
    private javax.swing.JButton btnteilEinlagern;
    private javax.swing.JLabel lblAktionSelektiert;
    private javax.swing.JLabel lblTeilebestand;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JScrollPane scpMain;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
