/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helper.FilterUiHelper;
import helper.Misc;
import java.awt.Component;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import model.Lager;
import model.collection.WarenbewegungCollection;
import model.filter.WarenbewegungFilterModel;
import model.table.WarenbewegungTableModel;

/**
 *
 * @author simon
 */
public class WarenbewegungFilterFrame extends javax.swing.JFrame {
    private static WarenbewegungFilterFrame singleton;
    JTable warenbewegungTable;
    
    public static WarenbewegungFilterFrame getInstance(Component mainFrame, JTable jtable)
    {
        if (WarenbewegungFilterFrame.singleton == null){
            singleton = new WarenbewegungFilterFrame(mainFrame, jtable);
        }
        singleton.setVisible(true);
        return singleton;
    }
    
    /**
     * Creates new form WarenbewegungFilterFrame
     */
    public WarenbewegungFilterFrame() {
        initComponents();
        try{
            loadCbx();
        }catch(SQLException ex){
            Misc.printSQLException(this, ex);
        }
    }

    public WarenbewegungFilterFrame(Component c, JTable jtable) {
        this();
        alignFilterMenu(c);
        warenbewegungTable = jtable;
    }
    
    public void alignFilterMenu(Component main)
    {
        int x = main.getX();
        int width = main.getPreferredSize().width;
        int rightBorder = x+width;
        int newOrigin = rightBorder -this.getWidth()-9;
        this.setLocation(newOrigin, this.getY()+210);
    }
    
    
    /**
     * Läd Quell und ZielComboBoxen mit den größtmöglichen Werten
     * @author ssinger
     * @throws SQLException 
     */
    private void loadCbx() throws SQLException {
        cbxQuelleZ.removeAllItems();
        cbxQuelleX.removeAllItems();
        cbxQuelleY.removeAllItems();
        cbxZielZ.removeAllItems();
        cbxZielX.removeAllItems();
        cbxZielY.removeAllItems();
        cbxQuelleZ.addItem("z");
        cbxQuelleX.addItem("x");
        cbxQuelleY.addItem("y");
        cbxZielZ.addItem("z");
        cbxZielX.addItem("x");
        cbxZielY.addItem("y");

        int x = 0;
        int y = 0;
        int z = 0;

        Lager fl = Lager.getLager(Lager.Lagerort.freilager);
        Lager hl = Lager.getLager(Lager.Lagerort.hochregal);

        if (hl.getHoehe() > fl.getHoehe()) {
            x = hl.getHoehe();
        } else {
            x = fl.getHoehe();
        }

        if (hl.getBreite() > fl.getBreite()) {
            y = hl.getBreite();
        } else {
            y = fl.getBreite();
        }

        if (hl.getTiefe() > fl.getTiefe()) {
            z = hl.getTiefe();
        } else {
            z = fl.getTiefe();
        }

        for (int i = 1; i <= x; i++) {
            cbxQuelleZ.addItem(i);
            cbxZielZ.addItem(i);
        }

        for (int i = 1; i <= y; i++) {
            cbxQuelleX.addItem(i);
            cbxZielX.addItem(i);
        }

        for (int i = 1; i <= z; i++) {
            cbxQuelleY.addItem(i);
            cbxZielY.addItem(i);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        txfDatumBis = new javax.swing.JTextField();
        cbxQuelleLagertyp = new javax.swing.JComboBox();
        lblQuellfach = new javax.swing.JLabel();
        lblTeiltyp = new javax.swing.JLabel();
        lblDatumBis = new javax.swing.JLabel();
        cbxTeiltyp = new javax.swing.JComboBox();
        lblFilter = new javax.swing.JLabel();
        cbxQuelleZ = new javax.swing.JComboBox();
        cbxZielZ = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        cbxQuelleX = new javax.swing.JComboBox();
        lblBewegungsTyp = new javax.swing.JLabel();
        cbxZielLagertyp = new javax.swing.JComboBox();
        lblZielfachadresse = new javax.swing.JLabel();
        cbxQuelleY = new javax.swing.JComboBox();
        btnFilterAusführen = new javax.swing.JButton();
        cbxZielX = new javax.swing.JComboBox();
        lblDatumVon = new javax.swing.JLabel();
        cbxZielY = new javax.swing.JComboBox();
        txfDatumVon = new javax.swing.JTextField();
        lblBewegungsDatum = new javax.swing.JLabel();
        lblHaltbarkeitsdatum = new javax.swing.JLabel();
        lblhaltbarVon = new javax.swing.JLabel();
        lblHaltbarBis = new javax.swing.JLabel();
        txfHaltbarVon = new javax.swing.JTextField();
        txfHaltbarBis = new javax.swing.JTextField();
        cbxBewegungsTyp = new javax.swing.JComboBox();
        lblBezeichnung = new javax.swing.JLabel();
        txfBezeichnung = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxQuelleLagertyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"", "FL", "HL" }));

        lblQuellfach.setText("Quellfachadresse:");

        lblTeiltyp.setText("Typ:");

        lblDatumBis.setText(" bis:");

        cbxTeiltyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Kaufteile", "Werkzeuge", "unfertige Baugruppe", "Vorratsteile", "Vorrichtungen" }));

        lblFilter.setText("Filter:");

        cbxQuelleZ.setModel(new javax.swing.DefaultComboBoxModel());

        cbxZielZ.setModel(new javax.swing.DefaultComboBoxModel());

        cbxQuelleX.setModel(new javax.swing.DefaultComboBoxModel());
        cbxQuelleX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxQuelleXActionPerformed(evt);
            }
        });

        lblBewegungsTyp.setText("Bewegungs-Typ:");

        cbxZielLagertyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "FL", "HL" }));

        lblZielfachadresse.setText("Zielfachadresse:");

        cbxQuelleY.setModel(new javax.swing.DefaultComboBoxModel());

        btnFilterAusführen.setText("Filter ausführen");
        btnFilterAusführen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterAusführenActionPerformed(evt);
            }
        });

        cbxZielX.setModel(new javax.swing.DefaultComboBoxModel());
        cbxZielX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxZielXActionPerformed(evt);
            }
        });

        lblDatumVon.setText("von:");

        cbxZielY.setModel(new javax.swing.DefaultComboBoxModel());

        lblBewegungsDatum.setText("Bewegungsdatum:");

        lblHaltbarkeitsdatum.setText("Haltbarkeitsdatum:");

        lblhaltbarVon.setText("von:");

        lblHaltbarBis.setText("bis:");

        txfHaltbarVon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfHaltbarVonActionPerformed(evt);
            }
        });

        cbxBewegungsTyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "einlagern", "auslagern", "umlagern", "splitten" }));

        lblBezeichnung.setText("Bezeichnung:");

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuellfach)
                            .addComponent(lblZielfachadresse)
                            .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbxBewegungsTyp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxTeiltyp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTeiltyp, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnFilterAusführen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBewegungsTyp, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFilter, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panMainLayout.createSequentialGroup()
                                    .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDatumVon)
                                        .addComponent(lblDatumBis))
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txfDatumVon, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(txfDatumBis)))
                                .addComponent(lblBewegungsDatum, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHaltbarkeitsdatum, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panMainLayout.createSequentialGroup()
                                    .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblhaltbarVon)
                                        .addComponent(lblHaltbarBis))
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txfHaltbarVon, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(txfHaltbarBis)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panMainLayout.createSequentialGroup()
                                    .addComponent(lblBezeichnung)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txfBezeichnung))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panMainLayout.createSequentialGroup()
                                    .addComponent(cbxQuelleLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxQuelleX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxQuelleY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxQuelleZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panMainLayout.createSequentialGroup()
                                    .addComponent(cbxZielLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxZielX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxZielY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxZielZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addComponent(lblFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBezeichnung)
                    .addComponent(txfBezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHaltbarkeitsdatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhaltbarVon)
                    .addComponent(txfHaltbarVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHaltbarBis)
                    .addComponent(txfHaltbarBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblBewegungsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVon)
                    .addComponent(txfDatumVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumBis)
                    .addComponent(txfDatumBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuellfach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxQuelleLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxQuelleX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxQuelleY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxQuelleZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblZielfachadresse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxZielLagertyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxZielZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxZielX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxZielY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBewegungsTyp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                .addComponent(cbxBewegungsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTeiltyp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTeiltyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFilterAusführen)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxQuelleXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxQuelleXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxQuelleXActionPerformed

    private void cbxZielXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxZielXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxZielXActionPerformed

    /**
     * Validiert die Eingabe, erzeugt ein neues LagerbestandFilterModel und
     * refreshed die Lagerbestandstabelle 
     */
    private void btnFilterAusführenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterAusführenActionPerformed
        HashMap<Integer, String> errors = FilterUiHelper.getInstance().validateWarenbewegungFilter(
                txfDatumVon.getText(),
                txfDatumBis.getText(),
                txfHaltbarVon.getText(),
                txfHaltbarBis.getText());
        
        if (Misc.createErrorDialog(this, errors) == true) {
            return;
        }
        
        WarenbewegungFilterModel wfm = FilterUiHelper.createWFM(
               txfBezeichnung.getText(),
               txfHaltbarVon.getText(),
               txfHaltbarBis.getText(),
               cbxQuelleLagertyp.getSelectedItem().toString(),
               cbxBewegungsTyp.getSelectedItem().toString(),
               cbxQuelleX.getSelectedItem().toString(),
               cbxQuelleY.getSelectedItem().toString(),
               cbxQuelleZ.getSelectedItem().toString(),
               cbxTeiltyp.getSelectedItem().toString(),
               cbxZielLagertyp.getSelectedItem().toString(),
               cbxZielX.getSelectedItem().toString(),
               cbxZielY.getSelectedItem().toString(),
               cbxZielZ.getSelectedItem().toString(),
               txfDatumVon.getText(),
               txfDatumBis.getText(),
               cbxBewegungsTyp.getSelectedItem().toString());
        
        try{
           refreshWarenbewegungTableModel(wfm);
          
        }catch (SQLException e){
          Misc.printSQLException(this, e);
        }
        this.dispose();
    }//GEN-LAST:event_btnFilterAusführenActionPerformed

    /**
     * Läd die Warenbewegungstabelle mit den übergebenen Filtereinstellungen
     * nach
     * @param wfm
     * @throws SQLException 
     */
    private void refreshWarenbewegungTableModel(WarenbewegungFilterModel wfm) throws SQLException{
        WarenbewegungCollection wc = WarenbewegungCollection.getInstance().applyFilter(wfm);
        WarenbewegungTableModel wm = new WarenbewegungTableModel();
        wm.setData(wc);
        warenbewegungTable.setModel(wm);
        TableCellRenderer ren = new TwoLinesCellRenderer();
        warenbewegungTable.getColumnModel().getColumn(5).setCellRenderer(ren);

        int[] arrWidths = {23, 120, 65, 70, 40, 170, 90, 65, 65, 90};
        TableColumn tc;
        warenbewegungTable.setRowHeight(23);
        int i = 0;
        for (int width : arrWidths) {
            tc = warenbewegungTable.getColumnModel().getColumn(i++);
            tc.setPreferredWidth(width);
        }
    }
    
    private void txfHaltbarVonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfHaltbarVonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfHaltbarVonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarenbewegungFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarenbewegungFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarenbewegungFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarenbewegungFilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarenbewegungFilterFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilterAusführen;
    private javax.swing.JComboBox cbxBewegungsTyp;
    private javax.swing.JComboBox cbxQuelleLagertyp;
    private javax.swing.JComboBox cbxQuelleX;
    private javax.swing.JComboBox cbxQuelleY;
    private javax.swing.JComboBox cbxQuelleZ;
    private javax.swing.JComboBox cbxTeiltyp;
    private javax.swing.JComboBox cbxZielLagertyp;
    private javax.swing.JComboBox cbxZielX;
    private javax.swing.JComboBox cbxZielY;
    private javax.swing.JComboBox cbxZielZ;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBewegungsDatum;
    private javax.swing.JLabel lblBewegungsTyp;
    private javax.swing.JLabel lblBezeichnung;
    private javax.swing.JLabel lblDatumBis;
    private javax.swing.JLabel lblDatumVon;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblHaltbarBis;
    private javax.swing.JLabel lblHaltbarkeitsdatum;
    private javax.swing.JLabel lblQuellfach;
    private javax.swing.JLabel lblTeiltyp;
    private javax.swing.JLabel lblZielfachadresse;
    private javax.swing.JLabel lblhaltbarVon;
    private javax.swing.JPanel panMain;
    private javax.swing.JTextField txfBezeichnung;
    private javax.swing.JTextField txfDatumBis;
    private javax.swing.JTextField txfDatumVon;
    private javax.swing.JTextField txfHaltbarBis;
    private javax.swing.JTextField txfHaltbarVon;
    // End of variables declaration//GEN-END:variables
}
